defaults:
  - paths: default
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

seed: 0

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: null
pretrained_feature_extractor: null

backbone:
  name: "resnet50"

method: "mocov3"
pretrain_method: "mocov3"

data:
  dataset: "imagenet100"
  train_path: ${paths.data_train_path}
  val_path: ${paths.data_val_path}
  train_backgrounds: [ 's1', 's2', 's3', 's4', 's5', 's6' ]
  val_backgrounds: [ 's7', 's8', 's9', 's10', 's11' ]
  num_workers: 8
optimizer:
  name: "sgd"
  batch_size: 128
  lr: 0.1
  weight_decay: 0
  momentum: 0.9
scheduler:
  name: "warmup_cosine"
  warmup_start_lr: 0.00001
  warmup_epochs: 0
  max_epochs: 100
  interval: "epoch"
checkpoint:
  enabled: True
  dir: ${paths.checkpoint_dir}
  frequency: 1
  save_last: True
auto_resume:
  enabled: False
early_stopping:
  enabled: False
  patience: 5
  monitor: "val_acc1"
  mode: "max"

use_pre_extract_feats: False
skip_pre_extraction_of_feats: False
finetune: False

grid:
  enabled: True
  lr: [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 3.0]

# overwrite PL stuff
max_epochs: 100
devices: 8
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
log_every_n_steps: 50